### ISSUE TITLE
Crash when calling `identify`

### ISSUE THREAD

**Issue by janlat** [appcues/appcues-react-native-module#63] opened 2023-01-09 21:24 UTC
Hey,
Since I've included Appcues in my app, I started seeing a small number of crash reports caused by
```
Exception kotlin.UninitializedPropertyAccessException:
  at com.appcuesreactnative.AppcuesReactNativeModule.identify (AppcuesReactNativeModule.kt:122)
```
On the JS side, I'm definitely calling `setup` before `identify`, so would that mean that `setup` is not fully synchronous? And if so, is there anything I can do to check when it's finished?

**Comment by iujames** [comment] 2023-01-10 16:42
Hi @janlat - thank you for bringing this to our attention! I believe we have found the root cause here, related to how react native modules bridge calls to the native implementations [asynchronously](https://reactnative.dev/docs/0.62/native-modules-android#:~:text=React%20Native%20bridge%20is%20asynchronous). This could lead to a race condition, where the implementation was not initialized before the next function call attempted to use it - just as you noted.

#64 is the proposed fix under review now, please let us know if you have any feedback. Once an update is merged, we'll immediately release a `1.2.1` version update to this package that you can use and hopefully resolve any crash reports like the one referenced here.

Thanks!

**Comment by janlat** [comment] 2023-01-10 20:43
Returning a promise from `setup` is :ok_hand: 
Thank you for the quick fix!

**Closed** 2023-01-10 21:21 UTC
Labels: bug

**Comment by iujames** [comment] 2023-01-10 21:25
Excellent! The `1.2.1` update for `@appcues/react-native` is now published to npm.
